#Saeleen Worlds Apart save slot 1
#Sat Sep 19 02:31:15 EDT 2026
abilitySlots=1
coinCount=0
direction=0
enemy0.dmg=10
enemy0.health=50
enemy0.isPlayerInVision=false
enemy0.isWalkingLeft=false
enemy0.level=1
enemy0.maxHealth=50
enemy0.posX=3239.9832
enemy0.posY=1900.0
enemy0.startPosX=3130.0
enemy0.startPosY=1900.0
enemy0.type=Soldier
enemy0.xpGiven=50
enemy1.dmg=10
enemy1.health=50
enemy1.isPlayerInVision=false
enemy1.isWalkingLeft=false
enemy1.level=1
enemy1.maxHealth=50
enemy1.posX=3329.9832
enemy1.posY=2000.0
enemy1.startPosX=3220.0
enemy1.startPosY=2000.0
enemy1.type=Soldier
enemy1.xpGiven=50
enemyCount=2
experience=200
health=225
item0.posX=3520.0
item0.posY=2010.0
item0.type=Apple
item1.posX=3500.0
item1.posY=2012.0
item1.type=Apple
item2.posX=3550.0
item2.posY=2020.0
item2.type=Apple
item3.posX=3960.0
item3.posY=1815.0
item3.type=Apple
item4.posX=3930.0
item4.posY=1803.0
item4.type=Apple
item5.posX=3990.0
item5.posY=1800.0
item5.type=Apple
item6.posX=3650.0
item6.posY=1750.0
item6.type=Mana Potion
itemCount=7
items=Mana Potion,Mana Potion
level=3
mana=112
maxHealth=225
maxMana=112
openstMSlots=1
playerGold=70
posX=3829.233
posY=1864.7401
spellChoice=1
spellChoice2=0
xpToLastLevel=0
xpToLevel=400
