#Saeleen Worlds Apart save slot 1
#Fri Sep 18 19:17:24 EDT 2026
abilitySlots=1
coin0.posX=2261.0
coin0.posY=1480.0
coin0.value=10
coin1.posX=2301.0
coin1.posY=1540.0
coin1.value=10
coin2.posX=2241.0
coin2.posY=1520.0
coin2.value=10
coin3.posX=2386.0
coin3.posY=1580.0
coin3.value=10
coin4.posX=2366.0
coin4.posY=1620.0
coin4.value=10
coin5.posX=2233.0
coin5.posY=1652.0
coin5.value=10
coin6.posX=3109.0
coin6.posY=1780.0
coin6.value=10
coin7.posX=3149.0
coin7.posY=1840.0
coin7.value=10
coin8.posX=3089.0
coin8.posY=1820.0
coin8.value=10
coinCount=9
direction=0
enemy0.dmg=10
enemy0.health=20
enemy0.isPlayerInVision=false
enemy0.isWalkingLeft=false
enemy0.level=1
enemy0.maxHealth=50
enemy0.posX=3876.4834
enemy0.posY=1900.0
enemy0.startPosX=3130.0
enemy0.startPosY=1900.0
enemy0.type=Soldier
enemy0.xpGiven=50
enemy1.dmg=10
enemy1.health=50
enemy1.isPlayerInVision=false
enemy1.isWalkingLeft=false
enemy1.level=1
enemy1.maxHealth=50
enemy1.posX=3966.4834
enemy1.posY=2000.0
enemy1.startPosX=3220.0
enemy1.startPosY=2000.0
enemy1.type=Soldier
enemy1.xpGiven=50
enemyCount=2
experience=200
health=225
item0.posX=3520.0
item0.posY=2010.0
item0.type=Apple
item1.posX=3500.0
item1.posY=2012.0
item1.type=Apple
item2.posX=3550.0
item2.posY=2020.0
item2.type=Apple
item3.posX=3960.0
item3.posY=1815.0
item3.type=Apple
item4.posX=3930.0
item4.posY=1803.0
item4.type=Apple
item5.posX=3990.0
item5.posY=1800.0
item5.type=Apple
item6.posX=2281.0
item6.posY=1500.0
item6.type=Mana Potion
item7.posX=2406.0
item7.posY=1600.0
item7.type=Mana Potion
item8.posX=2253.0
item8.posY=1672.0
item8.type=Mana Potion
itemCount=9
items=
level=3
mana=112
maxHealth=225
maxMana=112
openstMSlots=1
playerGold=0
posX=2698.5295
posY=1753.9403
spellChoice=1
xpToLastLevel=0
xpToLevel=400
